### ISSUE TITLE
FireBase Authentication fails

### ISSUE THREAD

**Issue by AniG007** [nisiddharth/HealthCastle#1]
It's pretty obvious that firebase would fail without the JSON file. So could you build an APK, upload it to Gdrive and paste the link back here? I liked your app concept and wanted to check it out.

**Comment by nisiddharth** [comment]
OK, [here is the link](https://drive.google.com/file/d/1aedgRhm36I5aONZsNLgUS3WSrRdAvzzQ/view?usp=sharing). I have added the link to README.md too. This is a debug APK, so not sure whether it will install on your device or not. Give it a try, if doesn't work then I will consider building a signed APK.

Also, since this project was built hastily in a hackathon, it has lots of unnecessary debugging lines. Captures images when it shouldn't, the alarm repeating times are too small, etc. So please spare us for that 🤐.

**Comment by AniG007** [comment]
Haha, it still says something fishy happened. It should have worked if you had included the JSON file and built it. See if it's working for you. Maybe it's something else. Anyways all the features that you've included sounds really good, so wanted to check em out.

**Comment by nisiddharth** [comment]
I've added screenshots to the repo for now. I'm currently somewhat busy. Will consider removing the caveats and building a signed apk after 1-2 months.

(I know this app is extremely useless without Firebase configurations JSON)
